django1/src/blog/urls.py
'''
Created on 2019. 4. 6.

@author: 405-6
'''
from customlogin.urls import app_name, urlpatterns
from blog.views import *
from django.urls.conf import path
app_name = 'blog'

urlpatterns = [ 
    #뷰 클래스는 as_view함수를 호출해서 URL을 등록
    #127.0.0.1:8000/blog/ 요청
    path('index/',Index.as_view(), name='index'),
    #DetailView 제네릭뷰는 pk라는 추가 매개변수를 사용함.
    #127.0.0.1:8000/blog/게시물숫자/
    path('<int:pk>/',DetailView.as_view(), name='detail'),
    #127.0.0.1:8000/blog/posting/
    path('posting/',Posting.as_view(), name='posting')
     ]

django1/src/django1/urls.py
from django.contrib import admin
from django.urls import path,include

from bookmark.views import index,book_list,book_one

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='main'),
    path('list/', book_list),
    path('<int:book_idx>/', book_one),
    path('vote/', include('vote.urls')),
    #127.0.0.1:8000/cl로 시작하는 url들을 customlogin 폴더의 urls.py에서 처리하도록 등록
    path('cl/',include('customlogin.urls')),
    #social_django 어플리케이션의 하위 URLConf 들록
    #우리가 만든 어플리케이션이 아니므로 app_name변수에 어떤 값이 있는지 확인이 어려움
    #include함수의 namespace매개변수: app_name변수를 무시하고 하위 그룹의 이름을 지정할 수 있음.
    path('auth/',include('social_django.urls',namespace= 'social')),
    path('blog/',include('blog.urls'))
    
    
]

#사용자가 이미지, 첨부파일 요청했을 때,
#웹서버 컴퓨터에 저장된 파일을 클라이언트에게 전달하도록 설정
#웹서버의 로컬 하드디스크와 URL주소를 연동

#setting.py 변수값을 사용할 수 있도록 임포트
from django.conf import settings
#MEDIA_URL과 MEDIA_ROOT를 연결하기 위한 함수 임포트
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django1/src/blog/models.py
from django.db import models

# Create your models here.
#카테고리
class Category(models.Model):
      name = models.CharField('카테고리', max_length=20)
      def __str__(self):
          return self.name

#글쓴이를 외래키로 지정하기 위한 User 모델 클래스 임포트
from django.contrib.auth.models import User
#글
#카테고리-외래키, 제목, 글쓴이-외래키, 글내용, 작성일
class Post(models.Model):
    #Category 모델 클래스와 1:n관계로 연결.
    #연결된 Category 객체가 삭제되려고 할 때, Post객체가 연결되어있으면
    #삭제가 안 되도록 설정
      category = models.ForeignKey(Category,on_delete=models.PROTECT)
      headline = models.CharField('제목', max_length=200)
      #User모델 클래스와 1:n관계로 연결.
      #User객체가 삭제되면 연결된 Post객체도 같이 삭제되도록 설정
      author = models.ForeignKey(User,on_delete=models.CASCADE)
      #TextField:글자수 제한이 없는 문자열 저장공간
      
      #default 외에 ???Field에서 사용할 수 있는 매개변수
      #null(기본값 False) : True값을 저장하면, 데이터 베이스에 객체 저장시, 해당 변수 없이 비어있어도 저장되도록 허용
      #blank(기본값 False) : True값을 저장하면, 폼 객체를 통한 사용자 입력 공간(<input>)제공시, 해당변수의 입력공간을 빈칸으로 허용
      #사용자가 입력하지 않아도 되고, 값이 비어있어도 데이터베이스에 저장되도록 설정
      content = models.TextField('내용',null=True, blank=True)
      #auto_now_add(DateTimeField, DateField만 사용 가능)
      #객체 생성시, 서버 기준의 날짜/시간이 자동으로 저장되도록 설정하는 매개변수
      pub_date = models.DateTimeField('작성일',auto_now_add=True)
      
      def __str__(self):
          return self.headline
      class Meta:
          #최신글 순으로 정렬(pub_date 값을 내림차순 정렬)
          ordering = ['-pub_date']
#글에 포함된 이미지 정보
#Post: 외래키, 이미지 저장 변수
class PostImage(models.Model):
    #연결된 글이 지워지면 이미지 객체도 같이 삭제되도록 설정
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    #ImageField : 이미지 파일을 저장하는 변수
    #필수 매개변수
    #upload_to : 실제 파일이 저장되는 경로를 지정하는 매개변수
    #서버 기준의 날짜/시간데이터를 포함시킬 수 있음
    #%Y: 서버 기준의 년도를 입력
    #%m: 서버 기준의 월를 입력
    #%d: 서버 기준의 일를 입력
    #객체 생성시, 실제 이미지 파일은 images/년도/월/일/폴더에 저장됨.
    image = models.ImageField('이미지 파일', upload_to='images/%Y/%m/%d')
#글에 포함된 첨부파일 정보
class PostFile(models.Model):
    post = models.ForeignKey(Post, on_delete= models.CASCADE)
   #(한글문서, 실행 파일, 이미지 파일, 등)
    file = models.FileField('첨부파일', upload_to='files/%y/%m/%d')
    
#ImageField를 사용하려면 Pillow 모듈이 파이썬에 설치되어야 함.
#Pillow : 파이썬에서 이미지 처리할 때 사용하는 대표적 모듈
#pip install Pillow    

django1/src/blog/forms.py
'''
Created on 2019. 4. 6.

@author: 405-6
'''

from blog.models import Post
from django import forms
#글쓰기에 사용할 폼클래스 - 모델 폼 클래스 상속
class PostForm(forms.ModelForm):
    #사용자가 첨부파일, 이미지를 업로드할 수 있도록 커스텀 입력양식 생성
    #이미지나 파일을 업로드하지 않아도 글을 쓸 수 있도록 커스텀 입력양식을 사용하는 것을 선택할 수 있도록 설정
    #->required 매개변서룰 False값을 설정
    
    #하나의 파일 업로드 입력 양식에 여러개의 파일을 동시에 업로드할 수 있도록 위젯 설정
    #->ClearableFileInput 위젯 설정
    files = forms.FileField(required=False,widget=forms.ClearableFileInput(attrs={'multiple':True}))
    images = forms.ImageField(required=False,widget=forms.ClearableFileInput(attrs={'multiple':True}))
    class Meta:
        model = Post
        fields = ['category','headline','content']

django1/src/blog/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from blog.models import Post, PostImage, PostFile
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

#클래스 기반의 뷰를 만들 때, 제네릭 뷰를 상속받아서 장고에서 제공하는 뷰 기능을 사용한다.

#제네릭 뷰: 장고에서 제공하는 여러가지 상황별 뷰 기능을 구현한 클래스

#index: 글 목록이 뜨는 메인 페이지
#ListView: 특정 모델 클래스의 객체 목록을 다루는 기능이 구현된 뷰
class Index(ListView):
    #사용자에게 전달할 HTML파일 경로
    template_name = 'blog/index.html'
    #리스트로 뽑을 모델 클래스 지정
    model = Post
    #템플릿에 객체 리스트를 전달할 때 사용할 변수명
    context_object_name = 'list'
    #한 페이지에 최대 몇 개의 객체가 보여질지 설정
    paginate_by = 5
#detail:글 상세보기 페이지
#DetailView: 특정 모델 클래스 객체 하나를 추출해서 템플릿에 넘겨주는 제네릭뷰
#DetailView는 request외에 추가 매개 변수를 사용해 추출할 객체를 찾음 -> pk 변수: id 값 같은 고유값으로 객체를 찾을 때 사용.

class Detail(DetailView):
    
    template_name = 'blog/detail.html'
    model = Post
    context_object_name = 'obj'    
    
from blog.forms import PostForm    
#posting: 글쓰기 페이지
#FormView : 특정 폼 클래스를 다루는 기능이 구현된 제네릭뷰
#LoginRequiredMixin:사용자가 비로그인 상태로 이 뷰를 요청한 경우, 로그인 페이지로 이동해주는 클래스
#뷰 함수 : 데코레이터, 뷰클래스 -> ???Mixin클래스 상속
class Posting(LoginRequiredMixin, FormView):
    
    template_name = 'blog/posting.html'
    #해당 뷰 클래스가 사용할 폼클래스 지정
    form_class = PostForm
    context_object_name = 'f'
    #is_valid()함수가 True를 반환한 뒤의 처리를 form_valid()에서
    #사용자가 준 추가 데이터를 처리하기 위해 해당 함수를 오버라이딩
    #매개변수 form: form_class 변수에 지정한 폼클래스객체가 저장됨.
    def form_valid(self, form):
        #PostForm 객체를 저장하기 전에 글쓴이 정보를 저장해야 함.
        #데이터 베이스에 바로 저장하지 않고 변동된 모델 클래스로 변환.
        #p: 사용자 입력으로 제목, 카테고리, 글 내용이 채워진 Post 객체(아직 데이터 베이스에 저장되지 않음)
        p = form.save(commit = False)
        #request.user : 요청한 클라이언트의 로그인 정보(User모델 클래스 객체)
        #이 요청을 한 클라이언트의 유저 정보를 Post 객체에 저장
        p.author = self.request.user
        p.save() # 데이터 베이스에 저장
        #사용자가 넘겨준 이미지, 파일마다 객체 생성
        #사용자가 넘겨준 이미지(첨부)파일마다 PostImage(PostFile) 객체 생성
        #request.FILES: 클라이언트가 서버로 보낸 파일 정보를 관리하는 변수(객체)
        #f: 사용자가 보낸 이미지 파일의 실제정보
        for f in self.request.FILES.getlist('images'):
            #새로운 PostImage객체를 생성(데이터 베이스에 저장 안 함)
            pi = PostImage()
            #이 요청으로 새로 만들어진 Post객체와 연결
            pi.post = p
            #사용자가 보낸 이미지 파일 정보를 변수에 저장
            pi.image = f
            pi.save() #데이터베이스에 새로운 PostImage객체 저장
        for f in self.request.FILES.getlist('files'):     
            pf = PostFile()
            pf.post = p
            pf.file = f
            pf.save()
         #완성된 글의 URL을 전달   
        return HttpResponseRedirect(reverse('blog:detail', args = (p.id,)))

django1/src/blog/templates/blog/detail.html
{% extends 'base.html' %}
{# obj : Post 객체  #}
{% block content %}
<h3>[{{obj.category}}] {{obj.headline}}</h3>
<p>{{obj.author}} / {{obj/pub_date}}</p>
<!-- obj 와 연동된 PostFile, PostImage객체를 추출 -->
{% for f in obj.postfile_set.all %}
 {#f : Post객체와 연동된 PostFile 객체. #}
 {# file.url : 파일을 다운받을 수 있는 URL주소를 저장한 변수 #}
 {#글에 연동된 첨부파일을 다운받을 수 있는 링크 제공#}
 <a download href="{{ f.file.url }}">{{f.file.name}}</a>
{% endfor %}

{% for f in obj.postimage_set.all %}
 {# 글과 연동된 이미지로 화면에 출력 #}
 <img src ="{{f.image.url}}" width="40%">
{% endfor %}
<pre>{{obj.content}}</pre>

{% endblock %}

django1/src/blog/templates/blog/index.html
{% extends 'base.html' %}
{# list : Post 모델 클래스 객체 리스트 #}
{% block content %}
<!-- 다음 페이지, 이전 페이지 링크
ListView가 넘겨주는 추가 변수
page_obj: 페이지 정보를 전달하는 변수

 -->
{% if page_obj.has_previous %}
<!--  href 속성에 URL주소를 기입 안 하면 현재 페이지 주소로 재요청함. ListView는 page 변수에 값을 보고 클라이언트에 몇 번째
페이지를 보여줄지 결정함 
page_obj.previous_page_number: 현재 페이지 기준 이전 페이지 번호가 저장된 변수
 
-->
 <a href ="?page={{page_obj.previous_page_number}}">이전 페이지</a>
{% endif %}

{% if page_obj.has_next %}
<a href ="?page={{page_obj.next_page_number}}">다음 페이지</a>
{% endif %}

<table width ="90%">
<tr>
<th>글번호</th>
<th>카테고리</th>
<th>제목</th>
<th>글쓴이</th>
<th>작성일</th>
</tr>
{% for p in list%}
<tr>
<th>{{p.id}}</th>
<th>{{p.category}}</th>
<th> <a href = "{% url 'blog:detail' p.id %}">
{{p.headline}}</a>
</th>
<th>{{p.author}}</th>
<th>{{p.pub_date}}</th> 
</tr>
{% endfor %}
</table>
<a href = "{% url 'blog:posting' %}">글쓰기</a>

{% endblock %}

django1/src/blog/templates/blog/posting.html
{% extends 'base.html' %}
{# f : PostForm 객체  #}

{% block content %}
<h3>글쓰기</h3>
<!--  enctype="multiple/form-data":해당 폼으로 파일데이터를 웹서버에 전달할 수 있도록 설정
파일을 업로드할 수 있는 입력공간이 있더라도 해당 설정이 없으면 request.FILES가 항상 비어있는 값이 전달됨 -->
<form action="" method="post" enctype="multipart/form-data">
 {% csrf_token %}
 <table>
  {{ form.as_table}}
 </table>
 <input type='submit' value="글쓰기">
</form>
<a href = "{% url 'blog:index' %}">메인 페이지로 돌아가기</a>
{% endblock %}